name: Atualizar Notícias

on:
  schedule:
    - cron: "0 */2 * * *"   # roda a cada 2 horas
  workflow_dispatch:         # permite rodar manualmente

jobs:
  atualizar-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install feedparser

      - name: Atualizar feed.json
        run: python update_feed.py

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add feed.json
          git commit -m "auto: atualizar feed" || echo "sem mudanças"
          git push
